import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RULES } from './definitions.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../../');

function ensureDir(filePath) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// -------------------------------------------------------------
// 1. Generate shared/generated/rules.js (GUI / JS)
// -------------------------------------------------------------
function generateJsRules() {
  const target = path.join(rootDir, 'shared/generated/rules.js');
  ensureDir(target);

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Source: shared/rules/definitions.js
 * Generated by: shared/rules/generator.js
 */

export const RULES = ${JSON.stringify(RULES, null, 2)};

export const ASN_REGEX = new RegExp(${JSON.stringify(RULES.asn.regexStr)});
export const PUBLIC_KEY_REGEX = new RegExp(${JSON.stringify(RULES.publicKey.regexStr)});
export const IPV4_REGEX = new RegExp(${JSON.stringify(RULES.ipv4.regexStr)});
export const IPV6_ULA_REGEX = new RegExp(${JSON.stringify(RULES.ipv6Ula.regexStr)});
export const LINK_LOCAL_REGEX = new RegExp(${JSON.stringify(RULES.linkLocal.regexStr)});

export function normalizeAsn(val) {
  if (val === null || val === undefined) return '';
  return String(val).trim().replace(/^AS/i, '');
}

export function calcDefaultPort(asn) {
  const cleanAsn = parseInt(normalizeAsn(asn), 10);
  if (isNaN(cleanAsn) || cleanAsn <= 0) return ${RULES.port.baseOffset + 1};
  return ${RULES.port.baseOffset} + (cleanAsn % ${RULES.port.modulo});
}

export function formatDefaultLinkLocal(asn) {
  const cleanAsn = normalizeAsn(asn);
  return cleanAsn ? \`fe80::\${cleanAsn}\` : 'fe80::1';
}

export function validateAsn(val) {
  const clean = normalizeAsn(val);
  if (!clean) return { valid: false, error: 'ASN is required' };
  if (!ASN_REGEX.test(clean)) return { valid: false, error: ${JSON.stringify(RULES.asn.errorMessage)} };
  const num = parseInt(clean, 10);
  if (num < ${RULES.asn.min} || num > ${RULES.asn.max}) {
    return { valid: false, error: ${JSON.stringify(RULES.asn.errorMessage)} };
  }
  return { valid: true, value: num };
}

export function validatePublicKey(val) {
  if (!val || typeof val !== 'string') return { valid: false, error: 'Public key is required' };
  const trimmed = val.trim();
  if (trimmed.length !== ${RULES.publicKey.length} || !PUBLIC_KEY_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.publicKey.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validateIpv4(val, isOptional = false) {
  if (!val || typeof val !== 'string' || !val.trim()) {
    if (isOptional) return { valid: true, value: null };
    return { valid: false, error: 'IPv4 address is required' };
  }
  const trimmed = val.trim();
  if (!IPV4_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.ipv4.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validateIpv6Ula(val, isOptional = false) {
  if (!val || typeof val !== 'string' || !val.trim()) {
    if (isOptional) return { valid: true, value: null };
    return { valid: false, error: 'IPv6 ULA is required' };
  }
  const trimmed = val.trim();
  if (!IPV6_ULA_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.ipv6Ula.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validateLinkLocal(val) {
  if (!val || typeof val !== 'string') return { valid: false, error: 'Link-Local address is required' };
  const trimmed = val.trim();
  if (!LINK_LOCAL_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.linkLocal.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validatePort(val, isOptional = false) {
  if (val === null || val === undefined || val === '' || val === 'auto') {
    if (isOptional || val === 'auto') return { valid: true, value: 'auto' };
    return { valid: false, error: 'Port is required' };
  }
  const num = parseInt(val, 10);
  if (isNaN(num) || num < ${RULES.port.min} || num > ${RULES.port.max}) {
    return { valid: false, error: ${JSON.stringify(RULES.port.errorMessage)} };
  }
  return { valid: true, value: num };
}

export function validateMtu(val) {
  if (val === null || val === undefined || val === '') return { valid: true, value: ${RULES.mtu.default} };
  const num = parseInt(val, 10);
  if (isNaN(num) || num < ${RULES.mtu.min} || num > ${RULES.mtu.max}) {
    return { valid: false, error: ${JSON.stringify(RULES.mtu.errorMessage)} };
  }
  return { valid: true, value: num };
}
`;

  fs.writeFileSync(target, content, 'utf8');
  console.log(`[build:rules] Generated ${target}`);
}

// -------------------------------------------------------------
// 2. Generate cli/cli-src/lib/rules.sh (Busybox CLI)
// -------------------------------------------------------------
function generateShellRules() {
  const target = path.join(rootDir, 'cli/cli-src/lib/rules.sh');
  ensureDir(target);

  const content = `#!/bin/sh
# AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
# Source: shared/rules/definitions.js
# Generated by: shared/rules/generator.js
#
# Busybox POSIX-compliant helper functions (0-fork, parameter expansion)

normalize_asn() {
  _asn="\${1#[aA][sS]}"
  _asn="\${_asn%% }"
  _asn="\${_asn## }"
  echo "$_asn"
}

calc_default_port() {
  _asn="$(normalize_asn "$1")"
  case "$_asn" in
    ''|*[!0-9]*) echo "${RULES.port.baseOffset + 1}" ;;
    *) echo "$(( ${RULES.port.baseOffset} + (_asn % ${RULES.port.modulo}) ))" ;;
  esac
}

validate_asn() {
  _val="$(normalize_asn "$1")"
  case "$_val" in
    ''|*[!0-9]*) return 1 ;;
  esac
  if [ \${#_val} -gt 10 ] || [ "$_val" -eq 0 ]; then
    return 1
  fi
  return 0
}

validate_pubkey() {
  _val="$1"
  _val="\${_val%% }"
  _val="\${_val## }"
  if [ \${#_val} -ne ${RULES.publicKey.length} ]; then
    return 1
  fi
  case "$_val" in
    *=) ;;
    *) return 1 ;;
  esac
  case "$_val" in
    *[!A-Za-z0-9+/=]*) return 1 ;;
  esac
  return 0
}

validate_ipv4() {
  _val="$1"
  _val="\${_val%% }"
  _val="\${_val## }"
  [ -z "$_val" ] && return 1
  _ip="\${_val%%/*}"
  case "$_ip" in
    *.*.*.*) ;;
    *) return 1 ;;
  esac
  _o1="\${_ip%%.*}"; _rest="\${_ip#*.}"
  _o2="\${_rest%%.*}"; _rest="\${_rest#*.}"
  _o3="\${_rest%%.*}"; _o4="\${_rest#*.}"
  for _o in "$_o1" "$_o2" "$_o3" "$_o4"; do
    case "$_o" in
      ''|*[!0-9]*) return 1 ;;
    esac
    if [ "$_o" -lt 0 ] || [ "$_o" -gt 255 ]; then
      return 1
    fi
  done
  return 0
}

validate_ipv6_ula() {
  _val="$1"
  _val="\${_val%% }"
  _val="\${_val## }"
  [ -z "$_val" ] && return 1
  case "$_val" in
    [fF][dD]*:*) return 0 ;;
    *) return 1 ;;
  esac
}

validate_link_local() {
  _val="$1"
  _val="\${_val%% }"
  _val="\${_val## }"
  [ -z "$_val" ] && return 1
  case "$_val" in
    [fF][eE]80:*|[fF][eE]80::*) return 0 ;;
    *) return 1 ;;
  esac
}

validate_port() {
  _val="$1"
  _val="\${_val%% }"
  _val="\${_val## }"
  [ "$_val" = "auto" ] && return 0
  case "$_val" in
    ''|*[!0-9]*) return 1 ;;
  esac
  if [ "$_val" -ge ${RULES.port.min} ] && [ "$_val" -le ${RULES.port.max} ]; then
    return 0
  fi
  return 1
}

validate_mtu() {
  _val="$1"
  _val="\${_val%% }"
  _val="\${_val## }"
  [ -z "$_val" ] && return 0
  case "$_val" in
    *[!0-9]*) return 1 ;;
  esac
  if [ "$_val" -ge ${RULES.mtu.min} ] && [ "$_val" -le ${RULES.mtu.max} ]; then
    return 0
  fi
  return 1
}
`;

  fs.writeFileSync(target, content, 'utf8');
  console.log(`[build:rules] Generated ${target}`);
}

// -------------------------------------------------------------
// 3. Generate server/utils/validator.js (Server Authoritative)
// -------------------------------------------------------------
function generateServerValidator() {
  const target = path.join(rootDir, 'server/utils/validator.js');
  ensureDir(target);

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Source: shared/rules/definitions.js
 * Generated by: shared/rules/generator.js
 *
 * Authoritative Server Format Validator
 */

export const RULES = ${JSON.stringify(RULES, null, 2)};

export const ASN_REGEX = new RegExp(${JSON.stringify(RULES.asn.regexStr)});
export const PUBLIC_KEY_REGEX = new RegExp(${JSON.stringify(RULES.publicKey.regexStr)});
export const IPV4_REGEX = new RegExp(${JSON.stringify(RULES.ipv4.regexStr)});
export const IPV6_ULA_REGEX = new RegExp(${JSON.stringify(RULES.ipv6Ula.regexStr)});
export const LINK_LOCAL_REGEX = new RegExp(${JSON.stringify(RULES.linkLocal.regexStr)});

export function normalizeAsn(val) {
  if (val === null || val === undefined) return '';
  return String(val).trim().replace(/^AS/i, '');
}

export function calcDefaultPort(asn) {
  const cleanAsn = parseInt(normalizeAsn(asn), 10);
  if (isNaN(cleanAsn) || cleanAsn <= 0) return ${RULES.port.baseOffset + 1};
  return ${RULES.port.baseOffset} + (cleanAsn % ${RULES.port.modulo});
}

export function validateAsn(val) {
  const clean = normalizeAsn(val);
  if (!clean) return { valid: false, error: 'ASN is required' };
  if (!ASN_REGEX.test(clean)) return { valid: false, error: ${JSON.stringify(RULES.asn.errorMessage)} };
  const num = parseInt(clean, 10);
  if (num < ${RULES.asn.min} || num > ${RULES.asn.max}) {
    return { valid: false, error: ${JSON.stringify(RULES.asn.errorMessage)} };
  }
  return { valid: true, value: num };
}

export function validatePublicKey(val) {
  if (!val || typeof val !== 'string') return { valid: false, error: 'WireGuard Public Key is required' };
  const trimmed = val.trim();
  if (trimmed.length !== ${RULES.publicKey.length} || !PUBLIC_KEY_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.publicKey.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validateIpv4(val, isOptional = false) {
  if (!val || typeof val !== 'string' || !val.trim()) {
    if (isOptional) return { valid: true, value: null };
    return { valid: false, error: 'IPv4 address is required' };
  }
  const trimmed = val.trim();
  if (!IPV4_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.ipv4.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validateIpv6Ula(val, isOptional = false) {
  if (!val || typeof val !== 'string' || !val.trim()) {
    if (isOptional) return { valid: true, value: null };
    return { valid: false, error: 'IPv6 ULA is required' };
  }
  const trimmed = val.trim();
  if (!IPV6_ULA_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.ipv6Ula.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validateLinkLocal(val) {
  if (!val || typeof val !== 'string') return { valid: false, error: 'Link-Local address is required' };
  const trimmed = val.trim();
  if (!LINK_LOCAL_REGEX.test(trimmed)) {
    return { valid: false, error: ${JSON.stringify(RULES.linkLocal.errorMessage)} };
  }
  return { valid: true, value: trimmed };
}

export function validatePort(val, isOptional = false) {
  if (val === null || val === undefined || val === '' || val === 'auto') {
    if (isOptional || val === 'auto') return { valid: true, value: 'auto' };
    return { valid: false, error: 'Port is required' };
  }
  const num = parseInt(val, 10);
  if (isNaN(num) || num < ${RULES.port.min} || num > ${RULES.port.max}) {
    return { valid: false, error: ${JSON.stringify(RULES.port.errorMessage)} };
  }
  return { valid: true, value: num };
}

export function validateMtu(val) {
  if (val === null || val === undefined || val === '') return { valid: true, value: ${RULES.mtu.default} };
  const num = parseInt(val, 10);
  if (isNaN(num) || num < ${RULES.mtu.min} || num > ${RULES.mtu.max}) {
    return { valid: false, error: ${JSON.stringify(RULES.mtu.errorMessage)} };
  }
  return { valid: true, value: num };
}

/**
 * Validate full peering submission payload (format rules only)
 * Returns { valid: boolean, fieldErrors: Record<string, string>, normalized: object }
 */
export function validatePeeringSubmission(payload = {}) {
  const fieldErrors = {};
  const normalized = {};

  // ASN
  const asnRes = validateAsn(payload.asn);
  if (!asnRes.valid) {
    fieldErrors.asn = asnRes.error;
  } else {
    normalized.asn = asnRes.value;
  }

  // Node ID (basic presence check)
  if (!payload.nodeId || typeof payload.nodeId !== 'string' || !payload.nodeId.trim()) {
    fieldErrors.nodeId = 'Node ID is required';
  } else {
    normalized.nodeId = payload.nodeId.trim();
  }

  // WireGuard Public Key
  const pubRes = validatePublicKey(payload.publicKey);
  if (!pubRes.valid) {
    fieldErrors.publicKey = pubRes.error;
  } else {
    normalized.publicKey = pubRes.value;
  }

  // Link-Local
  const llaRes = validateLinkLocal(payload.linkLocal);
  if (!llaRes.valid) {
    fieldErrors.linkLocal = llaRes.error;
  } else {
    normalized.linkLocal = llaRes.value;
  }

  // IPv4 (Optional if IPv6-only, but checked if present)
  if (payload.ipv4) {
    const v4Res = validateIpv4(payload.ipv4, true);
    if (!v4Res.valid) {
      fieldErrors.ipv4 = v4Res.error;
    } else {
      normalized.ipv4 = v4Res.value;
    }
  } else {
    normalized.ipv4 = null;
  }

  // IPv6 ULA (Optional if not allocated, but checked if present)
  if (payload.ipv6Ula) {
    const v6Res = validateIpv6Ula(payload.ipv6Ula, true);
    if (!v6Res.valid) {
      fieldErrors.ipv6Ula = v6Res.error;
    } else {
      normalized.ipv6Ula = v6Res.value;
    }
  } else {
    normalized.ipv6Ula = null;
  }

  // Endpoint (Peer endpoint hostname/IP)
  if (payload.endpoint) {
    normalized.endpoint = String(payload.endpoint).trim();
  } else {
    normalized.endpoint = '';
  }

  // ListenPort (Server-side hostPort, auto or integer)
  const portRes = validatePort(payload.listenPort || payload.port, true);
  if (!portRes.valid) {
    fieldErrors.listenPort = portRes.error;
  } else {
    normalized.listenPort = portRes.value;
  }

  // ClientPort (Client-side port, auto or integer)
  const clientPortRes = validatePort(payload.clientPort, true);
  if (!clientPortRes.valid) {
    fieldErrors.clientPort = clientPortRes.error;
  } else {
    normalized.clientPort = clientPortRes.value || 'auto';
  }

  // MTU
  const mtuRes = validateMtu(payload.mtu);
  if (!mtuRes.valid) {
    fieldErrors.mtu = mtuRes.error;
  } else {
    normalized.mtu = mtuRes.value;
  }

  // BGP Mode
  if (payload.bgpMode && !RULES.bgpMode.allowed.includes(payload.bgpMode)) {
    fieldErrors.bgpMode = RULES.bgpMode.errorMessage;
  } else {
    normalized.bgpMode = payload.bgpMode || RULES.bgpMode.default;
  }

  return {
    valid: Object.keys(fieldErrors).length === 0,
    fieldErrors,
    normalized
  };
}
`;

  fs.writeFileSync(target, content, 'utf8');
  console.log(`[build:rules] Generated ${target}`);
}

// -------------------------------------------------------------
// Run Generation
// -------------------------------------------------------------
console.log('--- Generating Shared Rules (1 Source -> 3 Targets) ---');
generateJsRules();
generateShellRules();
generateServerValidator();
console.log('--- Rules Generation Completed Successfully ---');
