#!/bin/sh
# AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
# Source: shared/rules/definitions.js
# Generated by: shared/rules/generator.js
#
# Busybox POSIX-compliant helper functions (0-fork, parameter expansion)

normalize_asn() {
  _asn="${1#[aA][sS]}"
  _asn="${_asn%% }"
  _asn="${_asn## }"
  echo "$_asn"
}

calc_default_port() {
  _asn="$(normalize_asn "$1")"
  case "$_asn" in
    ''|*[!0-9]*) echo "20001" ;;
    *) echo "$(( 20000 + (_asn % 10000) ))" ;;
  esac
}

validate_asn() {
  _val="$(normalize_asn "$1")"
  case "$_val" in
    ''|*[!0-9]*) return 1 ;;
  esac
  case "$_val" in
    424242[0-9][0-9][0-9][0-9]) return 0 ;;
  esac
  if [ "$_val" -ge 64512 ] 2>/dev/null && [ "$_val" -le 65534 ] 2>/dev/null; then
    return 0
  fi
  return 1
}

validate_pubkey() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  if [ ${#_val} -ne 44 ]; then
    return 1
  fi
  case "$_val" in
    *=) ;;
    *) return 1 ;;
  esac
  case "$_val" in
    *[!A-Za-z0-9+/=]*) return 1 ;;
  esac
  return 0
}

validate_ipv4() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  [ -z "$_val" ] && return 1
  _ip="${_val%%/*}"
  case "$_ip" in
    *.*.*.*) ;;
    *) return 1 ;;
  esac
  _o1="${_ip%%.*}"; _rest="${_ip#*.}"
  _o2="${_rest%%.*}"; _rest="${_rest#*.}"
  _o3="${_rest%%.*}"; _o4="${_rest#*.}"
  for _o in "$_o1" "$_o2" "$_o3" "$_o4"; do
    case "$_o" in
      ''|*[!0-9]*) return 1 ;;
    esac
    if [ "$_o" -lt 0 ] || [ "$_o" -gt 255 ]; then
      return 1
    fi
  done
  if [ "$_o1" -eq 172 ] && [ "$_o2" -ge 20 ] && [ "$_o2" -le 23 ]; then
    return 0
  fi
  if [ "$_o1" -eq 10 ]; then
    return 0
  fi
  return 1
}

validate_endpoint() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  [ -z "$_val" ] && return 0
  case "$_val" in
    http://*|https://*|wg://*) return 1 ;;
    *:*) return 1 ;;
    *[!A-Za-z0-9.-]*) return 1 ;;
    .*|-*|*.-|*.|*-) return 1 ;;
  esac
  return 0
}

validate_ipv6_ula() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  [ -z "$_val" ] && return 1
  case "$_val" in
    [fF][dD]*:*) return 0 ;;
    *) return 1 ;;
  esac
}

validate_link_local() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  [ -z "$_val" ] && return 1
  _addr="${_val%%/*}"
  case "$_addr" in
    [fF][eE]80:*|[fF][eE]80::*) ;;
    *) return 1 ;;
  esac
  case "$_addr" in
    *[!0-9a-fA-F:]*) return 1 ;;
    *:::*) return 1 ;;
  esac
  _temp="${_addr%::*}"
  _rest="${_addr#*::}"
  if [ "$_temp" != "$_addr" ]; then
    _combined="$_temp:$_rest"
  else
    _combined="$_addr"
  fi
  _combined="${_combined#:}"
  _combined="${_combined%:}"
  
  _old_ifs="$IFS"
  IFS=":"
  set -- $_combined
  IFS="$_old_ifs"
  
  for _group in "$@"; do
    [ -z "$_group" ] && continue
    if [ ${#_group} -gt 4 ]; then
      return 1
    fi
  done
  return 0
}

validate_port() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  [ "$_val" = "auto" ] && return 0
  case "$_val" in
    ''|*[!0-9]*) return 1 ;;
  esac
  if [ "$_val" -ge 1024 ] && [ "$_val" -le 65535 ]; then
    return 0
  fi
  return 1
}

validate_mtu() {
  _val="$1"
  _val="${_val%% }"
  _val="${_val## }"
  [ -z "$_val" ] && return 0
  case "$_val" in
    *[!0-9]*) return 1 ;;
  esac
  if [ "$_val" -ge 1280 ] && [ "$_val" -le 1500 ]; then
    return 0
  fi
  return 1
}
