/**
 * InstallScriptService (server/services/installScriptService.js)
 *
 * Dynamically generates the unified one-click installation shell script
 * for edge nodes (bird-lgproxy + probe-agent + systemd units).
 */

export function generateInstallProbeScript({ masterUrl }) {
  const url = (masterUrl || '').replace(/\/+$/, '');

  return `#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# AkiLab DN42 Unified Node Agent & LGProxy Installer
# Automatically generated by DN42 Portal Master (Zero-Credential Distribution)
# -----------------------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
  echo "[ERROR] This installation script must be run as root (e.g. sudo bash)." >&2
  exit 1
fi

NODE_ID_ARG="\${1:-}"
NODE_TOKEN_ARG="\${2:-}"

if [ -z "$NODE_ID_ARG" ] || [ -z "$NODE_TOKEN_ARG" ]; then
  echo "[ERROR] Missing required arguments: <NODE_ID> <DEDICATED_TOKEN>" >&2
  echo "Usage: curl -sSL https://<domain>/install-probe.sh | sudo bash -s -- <NODE_ID> <DEDICATED_TOKEN>" >&2
  exit 1
fi

echo "==============================================================================="
echo "       AkiLab DN42 Node Agent and Looking Glass Proxy Automated Installer"
echo "==============================================================================="
echo "Target Node ID: \${NODE_ID_ARG}"

MASTER_URL="${url}"

# 1. Install prerequisites
echo "[1/5] Updating package cache and installing prerequisites..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y -q || true
apt-get install -y -q curl nodejs wireguard-tools iproute2 || true

# 2. Setup bird-lgproxy
echo "[2/5] Setting up bird-lgproxy..."
if ! command -v bird-lgproxy >/dev/null 2>&1; then
  apt-get install -y -q bird-lgproxy || {
    echo "Notice: bird-lgproxy package not found directly via apt; continuing."
  }
fi

cat << 'EOF' > /etc/systemd/system/bird-lgproxy.service
[Unit]
Description=BIRD Looking Glass Proxy (AkiLab DN42)
After=network.target bird.service bird6.service
Wants=bird.service

[Service]
Type=simple
ExecStart=/usr/bin/bird-lgproxy -listen 127.0.0.1:5000
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now bird-lgproxy || true

# 3. Setup probe-agent
echo "[3/5] Setting up probe agent scripts and directories..."
mkdir -p /opt/dn42-probe /var/lib/dn42-probe

curl -sSL "\${MASTER_URL}/scripts/probe-agent.js" -o /opt/dn42-probe/probe-agent.js
chmod 755 /opt/dn42-probe/probe-agent.js

cat << EOF > /etc/default/dn42-probe
# AkiLab DN42 Probe Agent Configuration
PORTAL_MASTER_URL="\${MASTER_URL}"
CLAIM_NODE_ID="\${NODE_ID_ARG}"
CLAIM_TOKEN="\${NODE_TOKEN_ARG}"
NODE_ID=""
NODE_TOKEN=""
EOF
chmod 600 /etc/default/dn42-probe

# 4. Setup systemd service, timer, and path
echo "[4/5] Installing systemd units (service, timer, path)..."
cat << 'EOF' > /etc/systemd/system/dn42-probe.service
[Unit]
Description=AkiLab DN42 Node Probe Report Service
After=network.target

[Service]
Type=oneshot
WorkingDirectory=/opt/dn42-probe
EnvironmentFile=-/etc/default/dn42-probe
Environment="PORTAL_MASTER_URL="
Environment="CLAIM_NODE_ID="
Environment="CLAIM_TOKEN="
Environment="NODE_ID="
Environment="NODE_TOKEN="
ExecStart=/usr/bin/node /opt/dn42-probe/probe-agent.js
EOF

cat << 'EOF' > /etc/systemd/system/dn42-probe.timer
[Unit]
Description=Periodic fallback probe reporter (every 5 minutes)

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min
Unit=dn42-probe.service

[Install]
WantedBy=timers.target
EOF

cat << 'EOF' > /etc/systemd/system/dn42-probe.path
[Unit]
Description=Watch /etc/wireguard for changes and trigger probe agent
After=network.target

[Path]
PathModified=/etc/wireguard
Unit=dn42-probe.service

[Install]
WantedBy=multi-user.target
EOF

# 5. Enable and start
echo "[5/5] Enabling and starting systemd units..."
systemctl daemon-reload
systemctl enable --now dn42-probe.timer dn42-probe.path

echo "Triggering initial probe auto-claim and reporting..."
systemctl start dn42-probe.service || true

echo ""
echo "==============================================================================="
echo "Deployment complete!"
echo "  Probe agent will monitor /etc/wireguard and report heartbeats every 5 mins."
echo "  Check status with: systemctl status dn42-probe.service"
echo "==============================================================================="
`;
}

