/**
 * InstallScriptService (server/services/installScriptService.js)
 *
 * Dynamically generates the unified one-click installation shell script
 * for edge nodes (bird-lgproxy + probe-agent + systemd units).
 */

export function generateInstallProbeScript({ masterUrl }) {
  const url = (masterUrl || '').replace(/\/+$/, '');

  return `#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# AkiLab DN42 Unified Node Agent & LGProxy Installer
# Automatically generated by DN42 Portal Master (Zero-Credential Distribution)
# -----------------------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
  echo "[ERROR] This installation script must be run as root (e.g. sudo bash)." >&2
  exit 1
fi

NODE_ID_ARG="\${1:-}"
NODE_TOKEN_ARG="\${2:-}"

if [ -z "$NODE_ID_ARG" ] || [ -z "$NODE_TOKEN_ARG" ]; then
  echo "[ERROR] Missing required arguments: <NODE_ID> <DEDICATED_TOKEN>" >&2
  echo "Usage: curl -sSL https://<domain>/install-probe.sh | sudo bash -s -- <NODE_ID> <DEDICATED_TOKEN>" >&2
  exit 1
fi

echo "==============================================================================="
echo "       AkiLab DN42 Node Agent and Looking Glass Proxy Automated Installer"
echo "==============================================================================="
echo "Target Node ID: \${NODE_ID_ARG}"

MASTER_URL="${url}"

# 1. Install prerequisites
echo "[1/5] Updating package cache and installing prerequisites..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y -q || true
apt-get install -y -q curl wireguard-tools iproute2 || true

# Ensure Node.js >= 18 is installed for native fetch and AbortSignal support
NODE_MAJOR=0
if command -v node >/dev/null 2>&1; then
  NODE_MAJOR=$(node -v 2>/dev/null | tr -d 'v' | cut -d'.' -f1)
fi
if [ -z "\${NODE_MAJOR}" ] || [ "\${NODE_MAJOR}" -lt 18 ]; then
  echo "    Node.js is missing or < v18 (detected v\${NODE_MAJOR:-0}). Installing Node.js 20 LTS..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - || true
  apt-get install -y -q nodejs || true
fi

# 2. Setup bird-lgproxy (prebuilt Go binary, no apt dependency)
echo "[2/5] Setting up bird-lgproxy (Go binary)..."
case "$(uname -m)" in
  x86_64) LG_ARCH="amd64" ;;
  aarch64) LG_ARCH="arm64" ;;
  armv7l) LG_ARCH="arm" ;;
  i386|i686) LG_ARCH="386" ;;
  *) LG_ARCH="amd64" ;;
esac
LG_URL="https://github.com/xddxdd/bird-lg-go/releases/download/v1.4.8/bird-lgproxy-go-v1.4.8-linux-\${LG_ARCH}.tar.gz"
case "\${LG_ARCH}" in
  amd64) LG_SHA256="f2b1d937a41c5d068e7095fcd87bfadec3efbaedc19654e30049256afb296fbe" ;;
  arm64) LG_SHA256="7316e1d914fdbd308a27ce0bbc7e0a3bca604e7e49ef4cbe1c2beb8167c83c91" ;;
  arm)   LG_SHA256="d0f9c0245f9b580ce3b4764448324f55976cf295801cdabf70c7f884525c9fcd" ;;
  386)   LG_SHA256="f829da03f743526ef9478df531269c37e1733dbe01ee6274089a75585b1a2ee8" ;;
  *)     LG_SHA256="" ;;
esac

LG_TMP=$(mktemp -d)
if curl -fsSL "\${LG_URL}" -o "\${LG_TMP}/lg.tar.gz" 2>/dev/null; then
  if [ -n "\${LG_SHA256}" ]; then
    ACTUAL_HASH=$(sha256sum "\${LG_TMP}/lg.tar.gz" 2>/dev/null | awk '{print \$1}')
    if [ "\${ACTUAL_HASH}" != "\${LG_SHA256}" ]; then
      echo "    Warning: SHA256 checksum mismatch for bird-lgproxy. Aborting installation."
      rm -rf "\${LG_TMP}"
      LG_TMP=""
    fi
  fi
  if [ -n "\${LG_TMP}" ]; then
    tar -xzf "\${LG_TMP}/lg.tar.gz" -C "\${LG_TMP}"
    LG_BIN=$(find "\${LG_TMP}" -maxdepth 2 -type f \\( -name "bird-lgproxy-go" -o -name "bird-lgproxy" -o -name "lgproxy-go" \\) | head -n 1)
    if [ -n "\${LG_BIN}" ]; then
      install -m 755 "\${LG_BIN}" /usr/local/bin/bird-lgproxy
      echo "    bird-lgproxy installed from Go release (verified SHA256)."
    fi
    rm -rf "\${LG_TMP}"
  fi
else
  echo "Notice: bird-lgproxy download failed; LG-based BGP queries will be unavailable."
fi

cat << 'EOF' > /etc/systemd/system/bird-lgproxy.service
[Unit]
Description=BIRD Looking Glass Proxy (AkiLab DN42)
After=network.target bird.service bird6.service
Wants=bird.service

[Service]
Type=simple
ExecStart=/usr/local/bin/bird-lgproxy --listen 0.0.0.0:5000 --bird /run/bird/bird.ctl
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now bird-lgproxy || true

# 3. Setup probe-agent
echo "[3/5] Setting up probe agent scripts and directories..."
mkdir -p /opt/dn42-probe /var/lib/dn42-probe

curl -sSL "\${MASTER_URL}/scripts/probe-agent.js" -o /opt/dn42-probe/probe-agent.js
chmod 755 /opt/dn42-probe/probe-agent.js

cat << EOF > /etc/default/dn42-probe
# AkiLab DN42 Probe Agent Configuration
PORTAL_MASTER_URL="\${MASTER_URL}"
CLAIM_NODE_ID="\${NODE_ID_ARG}"
CLAIM_TOKEN="\${NODE_TOKEN_ARG}"
NODE_ID=""
NODE_TOKEN=""
EOF
chmod 600 /etc/default/dn42-probe

# 4. Setup systemd service, timer, and path
echo "[4/5] Installing systemd units (service, timer, path)..."
NODE_BIN=$(command -v node || echo "/usr/bin/node")
cat << EOF > /etc/systemd/system/dn42-probe.service
[Unit]
Description=AkiLab DN42 Node Probe Report Service
After=network.target

[Service]
Type=oneshot
WorkingDirectory=/opt/dn42-probe
EnvironmentFile=-/etc/default/dn42-probe
ExecStart=\${NODE_BIN} /opt/dn42-probe/probe-agent.js
EOF

cat << 'EOF' > /etc/systemd/system/dn42-probe.timer
[Unit]
Description=Periodic fallback probe reporter (every 1 minute)

[Timer]
OnBootSec=1min
OnUnitActiveSec=1min
Unit=dn42-probe.service

[Install]
WantedBy=timers.target
EOF

cat << 'EOF' > /etc/systemd/system/dn42-probe.path
[Unit]
Description=Watch /etc/wireguard and /etc/bird for changes and trigger probe agent
After=network.target

[Path]
PathModified=/etc/wireguard
PathModified=/etc/bird
Unit=dn42-probe.service

[Install]
WantedBy=multi-user.target
EOF

# 5. Enable and start
echo "[5/5] Enabling and starting systemd units..."
systemctl daemon-reload
systemctl enable --now dn42-probe.timer dn42-probe.path

echo "Triggering initial probe auto-claim and reporting..."
systemctl start dn42-probe.service || true

echo ""
echo "==============================================================================="
echo "Deployment complete!"
echo "  Probe agent will monitor /etc/wireguard and /etc/bird and report heartbeats every 1 min."
echo "  Check status with: systemctl status dn42-probe.service"
echo "==============================================================================="
`;
}

