import { ENV } from '../config.js';
import { getActiveConfig } from '../storage/configLoader.js';

export class NotificationService {
  /**
   * Send Telegram Notification on new/updated peering session
   */
  static async notifyPeeringSubmission(session, isNew = true) {
    if (!ENV.TELEGRAM_BOT_TOKEN || !ENV.TELEGRAM_CHAT_ID) {
      // Telegram notification not configured
      return false;
    }

    try {
      const config = getActiveConfig();
      const node = config.nodes.find(n => n.id === session.nodeId) || {};
      const actionText = isNew ? '🚀 <b>New Peering Application</b>' : '🔄 <b>Peering Session Updated</b>';

      // Constraint: ListenPort taken from session.hostPort (real allocated value)
      const hostPort = session.assigned?.hostPort || session.peering?.listenPort || 20001;
      const clientPort = session.assigned?.clientPort || session.peering?.clientPort || 23143;
      const peerEndpoint = session.peering?.endpoint || '<roaming>';

      let snippet = session.assigned?.serverWireguardSnippet;
      if (!snippet) {
        const pubKey = session.peering?.publicKey || '';
        const nodeV4 = node.tunnelIpv4?.replace(/\/.*$/, '') || '';
        const nodeUla = node.tunnelIpv6ULA?.replace(/\/.*$/, '') || '';
        const clientV4 = session.peering?.ipv4?.replace(/\/.*$/, '') || '';
        const clientUla = session.peering?.ipv6Ula?.replace(/\/.*$/, '') || '';

        const serverPostUpLines = [];
        if (clientV4 && nodeV4) {
          serverPostUpLines.push(`PostUp = ip addr del dev %i ${nodeV4}/32`);
          serverPostUpLines.push(`PostUp = ip addr add dev %i ${nodeV4}/32 peer ${clientV4}/32`);
        }
        if (clientUla && nodeUla) {
          serverPostUpLines.push(`PostUp = ip addr del dev %i ${nodeUla}/128`);
          serverPostUpLines.push(`PostUp = ip addr add dev %i ${nodeUla}/128 peer ${clientUla}/128`);
        }
        const serverPostUpBlock = serverPostUpLines.length > 0 ? serverPostUpLines.join('\n') + '\n' : '';

        const serverAddresses = [];
        if (node.tunnelIpv4) serverAddresses.push(`${node.tunnelIpv4.replace(/\/.*$/, '')}/32`);
        if (node.tunnelIpv6ULA) serverAddresses.push(`${node.tunnelIpv6ULA.replace(/\/.*$/, '')}/128`);
        if (node.tunnelIpv6LLA) serverAddresses.push(`${node.tunnelIpv6LLA.replace(/\/.*$/, '')}/64`);
        const serverAddressLine = serverAddresses.join(', ') || 'fe80::3143/64';

        let epLine = '';
        if (session.peering?.endpoint) {
          const cp = session.assigned?.clientPort || session.peering?.clientPort;
          epLine = cp ? `Endpoint = ${session.peering.endpoint}:${cp}\n` : `Endpoint = ${session.peering.endpoint}\n`;
        }
        snippet = `[Interface]
PrivateKey = <SERVER_PRIVATE_KEY>
Address = ${serverAddressLine}
${serverPostUpBlock}ListenPort = ${hostPort}
MTU = ${session.peering?.mtu || 1420}

[Peer]
PublicKey = ${pubKey}
${epLine}AllowedIPs = 172.16.0.0/12, 10.0.0.0/8, fd00::/8, fe80::/10
PersistentKeepalive = 25
`;
      }

      const escapeHtml = (str) => String(str ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

      const message = `${actionText}
━━━━━━━━━━━━━━━━━━
• <b>ASN</b>: <code>AS${escapeHtml(session.asn)}</code>
• <b>AS Name</b>: <code>${escapeHtml(session.mnt || session.asName || 'DN42 Member')}</code>
• <b>Node</b>: <code>${escapeHtml(session.nodeId)}</code> (${escapeHtml(node.name || '')})
• <b>PeerPort (Host)</b>: <code>${escapeHtml(hostPort)}</code>
• <b>ListenPort (Client)</b>: <code>${escapeHtml(clientPort)}</code>
• <b>WireGuard PubKey</b>: <code>${escapeHtml(session.peering?.publicKey || '')}</code>
• <b>Link-Local</b>: <code>${escapeHtml(session.peering?.linkLocal || '')}</code>
• <b>IPv4</b>: <code>${escapeHtml(session.peering?.ipv4 || 'N/A')}</code>
• <b>IPv6 ULA</b>: <code>${escapeHtml(session.peering?.ipv6Ula || 'N/A')}</code>
• <b>Peer Endpoint</b>: <code>${escapeHtml(peerEndpoint)}</code>
• <b>MTU</b>: <code>${escapeHtml(session.peering?.mtu || 1420)}</code>
• <b>BGP Mode</b>: <code>${escapeHtml(session.peering?.bgpMode || 'mpbgp_enh')}</code>
• <b>Session ID</b>: <code>${escapeHtml(session.id)}</code>
━━━━━━━━━━━━━━━━━━
<b>我方 Server 配置（贴入 /etc/wireguard/wgX.conf）</b>:
<pre>${escapeHtml(snippet.trim())}</pre>
━━━━━━━━━━━━━━━━━━
<i>Notification auto-generated by DN42 Peering Portal 2.0</i>`;

      const url = `https://api.telegram.org/bot${ENV.TELEGRAM_BOT_TOKEN}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: ENV.TELEGRAM_CHAT_ID,
          text: message,
          parse_mode: 'HTML',
          disable_web_page_preview: true
        }),
        signal: AbortSignal.timeout(5000)
      });

      return response.ok;
    } catch (err) {
      console.error('[NotificationService] Failed to send Telegram notification:', err.message);
      return false;
    }
  }

  /**
   * Send Telegram Notification on deleted/revoked peering session
   */
  static async notifySessionDeletion(session) {
    if (!ENV.TELEGRAM_BOT_TOKEN || !ENV.TELEGRAM_CHAT_ID) {
      return false;
    }

    try {
      const config = getActiveConfig();
      const node = config.nodes.find(n => n.id === session.nodeId) || {};
      const hostPort = session.assigned?.hostPort || session.peering?.listenPort || 'N/A';

      const escapeHtml = (str) => String(str ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

      const message = `🗑️ <b>Peering Session Revoked / Deleted</b>
━━━━━━━━━━━━━━━━━━
• <b>ASN</b>: <code>AS${escapeHtml(session.asn)}</code>
• <b>AS Name</b>: <code>${escapeHtml(session.mnt || session.asName || 'DN42 Member')}</code>
• <b>Node</b>: <code>${escapeHtml(session.nodeId)}</code> (${escapeHtml(node.name || '')})
• <b>Released Port</b>: <code>${escapeHtml(hostPort)}</code>
• <b>WireGuard PubKey</b>: <code>${escapeHtml(session.peering?.publicKey || '')}</code>
• <b>Session ID</b>: <code>${escapeHtml(session.id)}</code>
━━━━━━━━━━━━━━━━━━
<i>Notification auto-generated by DN42 Peering Portal 2.0</i>`;

      const url = `https://api.telegram.org/bot${ENV.TELEGRAM_BOT_TOKEN}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: ENV.TELEGRAM_CHAT_ID,
          text: message,
          parse_mode: 'HTML',
          disable_web_page_preview: true
        }),
        signal: AbortSignal.timeout(5000)
      });

      return response.ok;
    } catch (err) {
      console.error('[NotificationService] Failed to send Telegram deletion notification:', err.message);
      return false;
    }
  }
}
