import { ENV } from '../config.js';
import { getActiveConfig } from '../storage/configLoader.js';

export class NotificationService {
  /**
   * Send Telegram Notification on new/updated peering session
   */
  static async notifyPeeringSubmission(session, isNew = true) {
    if (!ENV.TELEGRAM_BOT_TOKEN || !ENV.TELEGRAM_CHAT_ID) {
      // Telegram notification not configured
      return false;
    }

    try {
      const config = getActiveConfig();
      const node = config.nodes.find(n => n.id === session.nodeId) || {};
      const actionText = isNew ? '🚀 *New Peering Application*' : '🔄 *Peering Session Updated*';

      // Constraint: ListenPort taken from session.hostPort (real allocated value)
      const hostPort = session.assigned?.hostPort || session.peering?.listenPort || 20001;
      const peerEndpoint = session.peering?.endpoint || '<roaming>';

      const message = `${actionText}
━━━━━━━━━━━━━━━━━━
• *ASN*: \`AS${session.asn}\`
• *AS Name*: \`${session.asName || 'DN42 Member'}\`
• *Node*: \`${session.nodeId}\` (${node.name || ''})
• *Assigned Port*: \`${hostPort}\`${session.assigned?.isShifted ? ' _(Auto-Shifted)_' : ''}
• *WireGuard PubKey*: \`${session.peering?.publicKey || ''}\`
• *Link-Local*: \`${session.peering?.linkLocal || ''}\`
• *IPv4*: \`${session.peering?.ipv4 || 'N/A'}\`
• *IPv6 ULA*: \`${session.peering?.ipv6Ula || 'N/A'}\`
• *Peer Endpoint*: \`${peerEndpoint}\`
• *MTU*: \`${session.peering?.mtu || 1420}\`
• *BGP Mode*: \`${session.peering?.bgpMode || 'mpbgp_enh'}\`
• *Session ID*: \`${session.id}\`
━━━━━━━━━━━━━━━━━━
_Notification auto-generated by DN42 Peering Portal 2.0_`;

      const url = `https://api.telegram.org/bot${ENV.TELEGRAM_BOT_TOKEN}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: ENV.TELEGRAM_CHAT_ID,
          text: message,
          parse_mode: 'Markdown',
          disable_web_page_preview: true
        })
      });

      return response.ok;
    } catch (err) {
      console.error('[NotificationService] Failed to send Telegram notification:', err.message);
      return false;
    }
  }
}
