import { ENV } from '../config.js';
import { getActiveConfig } from '../storage/configLoader.js';

export class NotificationService {
  /**
   * Send Telegram Notification on new/updated peering session
   */
  static async notifyPeeringSubmission(session, isNew = true) {
    if (!ENV.TELEGRAM_BOT_TOKEN || !ENV.TELEGRAM_CHAT_ID) {
      // Telegram notification not configured
      return false;
    }

    try {
      const config = getActiveConfig();
      const node = config.nodes.find(n => n.id === session.nodeId) || {};
      const actionText = isNew ? '🚀 <b>New Peering Application</b>' : '🔄 <b>Peering Session Updated</b>';

      // Constraint: ListenPort taken from session.hostPort (real allocated value)
      const hostPort = session.assigned?.hostPort || session.peering?.listenPort || 20001;
      const clientPort = session.assigned?.clientPort || session.peering?.clientPort || 23143;
      const peerEndpoint = session.peering?.endpoint || '<roaming>';

      let snippet = session.assigned?.serverWireguardSnippet;
      if (!snippet) {
        const pubKey = session.peering?.publicKey || '';
        const peerAllowedIps = [];
        if (session.peering?.ipv4) peerAllowedIps.push(`${session.peering.ipv4.replace(/\/.*$/, '')}/32`);
        if (session.peering?.ipv6Ula) peerAllowedIps.push(`${session.peering.ipv6Ula.replace(/\/.*$/, '')}/128`);
        if (session.peering?.linkLocal) peerAllowedIps.push(`${session.peering.linkLocal.replace(/\/.*$/, '')}/128`);
        if (peerAllowedIps.length === 0) peerAllowedIps.push('fe80::/128');

        let epLine = '';
        if (session.peering?.endpoint) {
          const cp = session.assigned?.clientPort || session.peering?.clientPort;
          epLine = cp ? `Endpoint = ${session.peering.endpoint}:${cp}\n` : `Endpoint = ${session.peering.endpoint}\n`;
        }
        snippet = `[Peer]\nPublicKey = ${pubKey}\n${epLine}AllowedIPs = ${peerAllowedIps.join(', ')}\n`;
      }

      const escapeHtml = (str) => String(str ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

      const message = `${actionText}
━━━━━━━━━━━━━━━━━━
• <b>ASN</b>: <code>AS${escapeHtml(session.asn)}</code>
• <b>AS Name</b>: <code>${escapeHtml(session.asName || 'DN42 Member')}</code>
• <b>Node</b>: <code>${escapeHtml(session.nodeId)}</code> (${escapeHtml(node.name || '')})
• <b>PeerPort (Host)</b>: <code>${escapeHtml(hostPort)}</code>
• <b>ListenPort (Client)</b>: <code>${escapeHtml(clientPort)}</code>
• <b>WireGuard PubKey</b>: <code>${escapeHtml(session.peering?.publicKey || '')}</code>
• <b>Link-Local</b>: <code>${escapeHtml(session.peering?.linkLocal || '')}</code>
• <b>IPv4</b>: <code>${escapeHtml(session.peering?.ipv4 || 'N/A')}</code>
• <b>IPv6 ULA</b>: <code>${escapeHtml(session.peering?.ipv6Ula || 'N/A')}</code>
• <b>Peer Endpoint</b>: <code>${escapeHtml(peerEndpoint)}</code>
• <b>MTU</b>: <code>${escapeHtml(session.peering?.mtu || 1420)}</code>
• <b>BGP Mode</b>: <code>${escapeHtml(session.peering?.bgpMode || 'mpbgp_enh')}</code>
• <b>Session ID</b>: <code>${escapeHtml(session.id)}</code>
━━━━━━━━━━━━━━━━━━
<b>我方 Server 配置（贴入 /etc/wireguard/wgX.conf）</b>:
<pre>${escapeHtml(snippet.trim())}</pre>
━━━━━━━━━━━━━━━━━━
<i>Notification auto-generated by DN42 Peering Portal 2.0</i>`;

      const url = `https://api.telegram.org/bot${ENV.TELEGRAM_BOT_TOKEN}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: ENV.TELEGRAM_CHAT_ID,
          text: message,
          parse_mode: 'HTML',
          disable_web_page_preview: true
        }),
        signal: AbortSignal.timeout(5000)
      });

      return response.ok;
    } catch (err) {
      console.error('[NotificationService] Failed to send Telegram notification:', err.message);
      return false;
    }
  }
}
