/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Source: shared/rules/definitions.js
 * Generated by: shared/rules/generator.js
 *
 * Authoritative Server Format Validator
 */

export const RULES = {
  "asn": {
    "name": "ASN",
    "description": "DN42 Autonomous System Number (1-10 digits, usually 424242xxxx)",
    "regexStr": "^(424242[0-9]{4}|[0-9]{1,10})$",
    "dn42RegexStr": "^424242[0-9]{4}$",
    "min": 1,
    "max": 4294967295,
    "example": "4242423143",
    "errorMessage": "ASN must be a valid number (e.g. 4242423143)"
  },
  "publicKey": {
    "name": "WireGuard Public Key",
    "description": "44-character Base64 encoded WireGuard Curve25519 public key ending with =",
    "regexStr": "^[A-Za-z0-9+/]{43}=$",
    "length": 44,
    "example": "yA+N64x7tN/4H1XqJd+7qf3K9z1V8uT5R7o+P2w8x1E=",
    "errorMessage": "WireGuard Public Key must be 44-character Base64 ending with ="
  },
  "ipv4": {
    "name": "IPv4 Address / Subnet",
    "description": "Valid IPv4 address (DN42 typically 172.20.0.0/14 or 10.0.0.0/8)",
    "regexStr": "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?:\\/(?:[0-9]|[12][0-9]|3[0-2]))?$",
    "example": "172.20.150.1",
    "errorMessage": "Invalid IPv4 address or CIDR"
  },
  "ipv6Ula": {
    "name": "IPv6 ULA",
    "description": "DN42 IPv6 Unique Local Address (starts with fd)",
    "regexStr": "^fd[0-9a-fA-F]{2}:[0-9a-fA-F:]+(?:\\/(?:[0-9]|[1-9][0-9]|1[01][0-9]|12[0-8]))?$",
    "example": "fd00:4242:3143::1",
    "errorMessage": "IPv6 ULA must start with fd (e.g. fd00:4242:3143::1)"
  },
  "linkLocal": {
    "name": "IPv6 Link-Local",
    "description": "IPv6 Link-Local Address (starts with fe80:)",
    "regexStr": "^fe80:[0-9a-fA-F:]+$",
    "example": "fe80::4242:3143",
    "errorMessage": "Link-Local Address must start with fe80: (e.g. fe80::4242:3143)"
  },
  "port": {
    "name": "WireGuard ListenPort",
    "description": "UDP port between 1024 and 65535. Default calculated from ASN",
    "min": 1024,
    "max": 65535,
    "baseOffset": 20000,
    "modulo": 10000,
    "conflictStep": 10000,
    "example": 23143,
    "errorMessage": "Port must be an integer between 1024 and 65535"
  },
  "mtu": {
    "name": "MTU",
    "description": "WireGuard MTU (default 1420)",
    "default": 1420,
    "min": 1280,
    "max": 1500,
    "errorMessage": "MTU must be between 1280 and 1500"
  },
  "bgpMode": {
    "name": "BGP Mode",
    "default": "mpbgp_enh",
    "allowed": [
      "mpbgp_enh",
      "dual_stack",
      "ipv6_only"
    ],
    "errorMessage": "BGP mode must be mpbgp_enh, dual_stack, or ipv6_only"
  }
};

export const ASN_REGEX = new RegExp("^(424242[0-9]{4}|[0-9]{1,10})$");
export const PUBLIC_KEY_REGEX = new RegExp("^[A-Za-z0-9+/]{43}=$");
export const IPV4_REGEX = new RegExp("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?:\\/(?:[0-9]|[12][0-9]|3[0-2]))?$");
export const IPV6_ULA_REGEX = new RegExp("^fd[0-9a-fA-F]{2}:[0-9a-fA-F:]+(?:\\/(?:[0-9]|[1-9][0-9]|1[01][0-9]|12[0-8]))?$");
export const LINK_LOCAL_REGEX = new RegExp("^fe80:[0-9a-fA-F:]+$");

export function normalizeAsn(val) {
  if (val === null || val === undefined) return '';
  return String(val).trim().replace(/^AS/i, '');
}

export function calcDefaultPort(asn) {
  const cleanAsn = parseInt(normalizeAsn(asn), 10);
  if (isNaN(cleanAsn) || cleanAsn <= 0) return 20001;
  return 20000 + (cleanAsn % 10000);
}

export function validateAsn(val) {
  const clean = normalizeAsn(val);
  if (!clean) return { valid: false, error: 'ASN is required' };
  if (!ASN_REGEX.test(clean)) return { valid: false, error: "ASN must be a valid number (e.g. 4242423143)" };
  const num = parseInt(clean, 10);
  if (num < 1 || num > 4294967295) {
    return { valid: false, error: "ASN must be a valid number (e.g. 4242423143)" };
  }
  return { valid: true, value: num };
}

export function validatePublicKey(val) {
  if (!val || typeof val !== 'string') return { valid: false, error: 'WireGuard Public Key is required' };
  const trimmed = val.trim();
  if (trimmed.length !== 44 || !PUBLIC_KEY_REGEX.test(trimmed)) {
    return { valid: false, error: "WireGuard Public Key must be 44-character Base64 ending with =" };
  }
  return { valid: true, value: trimmed };
}

export function validateIpv4(val, isOptional = false) {
  if (!val || typeof val !== 'string' || !val.trim()) {
    if (isOptional) return { valid: true, value: null };
    return { valid: false, error: 'IPv4 address is required' };
  }
  const trimmed = val.trim();
  if (!IPV4_REGEX.test(trimmed)) {
    return { valid: false, error: "Invalid IPv4 address or CIDR" };
  }
  return { valid: true, value: trimmed };
}

export function validateIpv6Ula(val, isOptional = false) {
  if (!val || typeof val !== 'string' || !val.trim()) {
    if (isOptional) return { valid: true, value: null };
    return { valid: false, error: 'IPv6 ULA is required' };
  }
  const trimmed = val.trim();
  if (!IPV6_ULA_REGEX.test(trimmed)) {
    return { valid: false, error: "IPv6 ULA must start with fd (e.g. fd00:4242:3143::1)" };
  }
  return { valid: true, value: trimmed };
}

export function validateLinkLocal(val) {
  if (!val || typeof val !== 'string') return { valid: false, error: 'Link-Local address is required' };
  const trimmed = val.trim();
  if (!LINK_LOCAL_REGEX.test(trimmed)) {
    return { valid: false, error: "Link-Local Address must start with fe80: (e.g. fe80::4242:3143)" };
  }
  return { valid: true, value: trimmed };
}

export function validatePort(val, isOptional = false) {
  if (val === null || val === undefined || val === '' || val === 'auto') {
    if (isOptional || val === 'auto') return { valid: true, value: 'auto' };
    return { valid: false, error: 'Port is required' };
  }
  const num = parseInt(val, 10);
  if (isNaN(num) || num < 1024 || num > 65535) {
    return { valid: false, error: "Port must be an integer between 1024 and 65535" };
  }
  return { valid: true, value: num };
}

export function validateMtu(val) {
  if (val === null || val === undefined || val === '') return { valid: true, value: 1420 };
  const num = parseInt(val, 10);
  if (isNaN(num) || num < 1280 || num > 1500) {
    return { valid: false, error: "MTU must be between 1280 and 1500" };
  }
  return { valid: true, value: num };
}

/**
 * Validate full peering submission payload (format rules only)
 * Returns { valid: boolean, fieldErrors: Record<string, string>, normalized: object }
 */
export function validatePeeringSubmission(payload = {}) {
  const fieldErrors = {};
  const normalized = {};

  // ASN
  const asnRes = validateAsn(payload.asn);
  if (!asnRes.valid) {
    fieldErrors.asn = asnRes.error;
  } else {
    normalized.asn = asnRes.value;
  }

  // Node ID (basic presence check)
  if (!payload.nodeId || typeof payload.nodeId !== 'string' || !payload.nodeId.trim()) {
    fieldErrors.nodeId = 'Node ID is required';
  } else {
    normalized.nodeId = payload.nodeId.trim();
  }

  // WireGuard Public Key
  const pubRes = validatePublicKey(payload.publicKey);
  if (!pubRes.valid) {
    fieldErrors.publicKey = pubRes.error;
  } else {
    normalized.publicKey = pubRes.value;
  }

  // Link-Local
  const llaRes = validateLinkLocal(payload.linkLocal);
  if (!llaRes.valid) {
    fieldErrors.linkLocal = llaRes.error;
  } else {
    normalized.linkLocal = llaRes.value;
  }

  // IPv4 (Optional if IPv6-only, but checked if present)
  if (payload.ipv4) {
    const v4Res = validateIpv4(payload.ipv4, true);
    if (!v4Res.valid) {
      fieldErrors.ipv4 = v4Res.error;
    } else {
      normalized.ipv4 = v4Res.value;
    }
  } else {
    normalized.ipv4 = null;
  }

  // IPv6 ULA (Optional if not allocated, but checked if present)
  if (payload.ipv6Ula) {
    const v6Res = validateIpv6Ula(payload.ipv6Ula, true);
    if (!v6Res.valid) {
      fieldErrors.ipv6Ula = v6Res.error;
    } else {
      normalized.ipv6Ula = v6Res.value;
    }
  } else {
    normalized.ipv6Ula = null;
  }

  // Endpoint (Peer endpoint hostname/IP)
  if (payload.endpoint) {
    normalized.endpoint = String(payload.endpoint).trim();
  } else {
    normalized.endpoint = '';
  }

  // ListenPort (auto or integer)
  const portRes = validatePort(payload.listenPort || payload.port, true);
  if (!portRes.valid) {
    fieldErrors.listenPort = portRes.error;
  } else {
    normalized.listenPort = portRes.value;
  }

  // MTU
  const mtuRes = validateMtu(payload.mtu);
  if (!mtuRes.valid) {
    fieldErrors.mtu = mtuRes.error;
  } else {
    normalized.mtu = mtuRes.value;
  }

  // BGP Mode
  if (payload.bgpMode && !RULES.bgpMode.allowed.includes(payload.bgpMode)) {
    fieldErrors.bgpMode = RULES.bgpMode.errorMessage;
  } else {
    normalized.bgpMode = payload.bgpMode || RULES.bgpMode.default;
  }

  return {
    valid: Object.keys(fieldErrors).length === 0,
    fieldErrors,
    normalized
  };
}
